name: 'Get apps from PR prefix'
description: 'Extracts and returns the apps from the PR prefix'
inputs:
  prefix:
    description: 'The prefix to extract the apps from'
    required: true
outputs:
  apps:
    description: 'The apps extracted from the prefix'
runs:
  using: 'node16'
  main: 'index.js'
