name: Test foo

on: 
  workflow_call:

jobs:
  test:
    name: Test foo
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      

      # Test
      - name: Run script
        run: |
          ${{ matrix.appScript.script }}