name: ☕ Test

on: 
  workflow_call:
    inputs:
      app: 
        type: string
        description: 'The app to test'
        required: true

jobs:
  test:
    name: Test ${{ github.event.inputs.app }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup
      - name: Run test suite for app
        uses: ./.github/actions/test