name: Test

on: 
  workflow_call:
    inputs:
      apps: 
        type: string
        description: 'The apps to test'
        required: true

jobs:
  get-test-scripts:
    name: Build test scripts
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.get-test-scripts.outputs.scripts }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get test scripts
        id: get-test-scripts
        uses: ./.github/actions/get-test-scripts
        with:
          apps: ${{ inputs.apps }}

  test:
    needs: get-test-scripts

    # In case of "misc", we don't want to run tests
    if: ${{ fromJson(needs.get-test-scripts.outputs.scripts)[0] != null }}

    strategy:
      fail-fast: true
      matrix:
          appScript: ${{ fromJson(needs.get-test-scripts.outputs.scripts) }}

    name: ${{ matrix.appScript.name }}
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Test
      - name: Run script
        run: |
          ${{ matrix.appScript.script }}