name: Testing workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Apps to test'
        required: true
        default: 'foo'
run-name: "Apps: ${{ github.event.inputs.apps }}"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.apps }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm -F ${{ github.event.inputs.apps }} run test:ci
